Advanced Array Creation & Shaping

#Goal: Moving beyond simple lists to generating structured data.

In [1]:
import numpy as np

# 1. Generating data (Essential for ML initialization)
# Create a 1D array of 12 elements from 0 to 11
arr = np.arange(12)

# 2. Reshaping into 3D (Think of this as 2 images of 3x2 pixels)
# -1 allows NumPy to calculate the remaining dimension automatically
matrix_3d = arr.reshape(2, 3, 2) 

print(f"3D Shape: {matrix_3d.shape}")
print(f"Total Elements: {matrix_3d.size}")
print(f"Data Type: {matrix_3d.dtype}")
print(f"Array:\n{matrix_3d}")

3D Shape: (2, 3, 2)
Total Elements: 12
Data Type: int64
Array:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


Randomness & Initialization

#Goal: Learning how to create "Weights" for models.

In [2]:
# Create a 3x3 matrix of random numbers between 0 and 1
random_matrix = np.random.rand(3, 3)

# Create a 3x3 identity matrix (Used in Linear Algebra)
identity = np.eye(3)

print("Random Weights:\n", random_matrix)
print("\nIdentity Matrix:\n", identity)

Random Weights:
 [[0.30513868 0.21121773 0.71333194]
 [0.98396867 0.72829547 0.41268189]
 [0.59005415 0.46745695 0.47216032]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Vectorization & Broadcasting (The "Speed" Test)

#Goal: Understanding why we never use for loops in NumPy.

In [3]:
# Create a large array to test speed
large_arr = np.arange(1_000_000)

# Vectorized Operation (Lightning fast)
%timeit large_arr * 2

# Broadcasting a 1D array across a 2D matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
row_vector = np.array([10, 20, 30])

# Every row in the matrix gets the row_vector added to it
result = matrix + row_vector

print("Broadcasting Result:\n", result)

2.39 ms ± 138 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Broadcasting Result:
 [[11 22 33]
 [14 25 36]]


Axis-Based Aggregations

#Goal: Learning how to calculate statistics for specific columns or rows.

In [4]:
data = np.array([
    [10, 20, 30], # Student 1 scores
    [40, 50, 60]  # Student 2 scores
])

# Axis 0 = Vertical (Columns) | Axis 1 = Horizontal (Rows)
column_means = np.mean(data, axis=0) # Mean score per subject
row_means = np.mean(data, axis=1)    # Mean score per student

print("Mean per Subject (Axis 0):", column_means)
print("Mean per Student (Axis 1):", row_means)

Mean per Subject (Axis 0): [25. 35. 45.]
Mean per Student (Axis 1): [20. 50.]
