#Array Basics & Reshaping

Goal: Understand how data is structured for Machine Learning.

In [9]:
import numpy as np

# 1. Create a 1D array of 12 elements
arr = np.arange(12)

# 2. Reshape into a 2D matrix (4 rows, 3 columns)
# This is how feature matrices are usually structured
matrix = arr.reshape(4, 3)

print("Original Array:", arr)
print("\n4x3 Matrix:\n", matrix)
print(f"\nShape: {matrix.shape} | Dimensions: {matrix.ndim}")

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

4x3 Matrix:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Shape: (4, 3) | Dimensions: 2


#Vectorization & Broadcasting

Goal: See how NumPy handles math efficiently without loops.

In [10]:
# Create a 2D matrix
data = np.array([[1, 2, 3], [4, 5, 6]])

# Scalar Broadcasting: Add 10 to every single element
plus_ten = data + 10

# Row Broadcasting: Add [100, 200, 300] to each row
row_modifier = np.array([100, 200, 300])
broadcasted_sum = data + row_modifier

print("Original Data:\n", data)
print("\nAfter Scalar Addition (+10):\n", plus_ten)
print("\nAfter Row-wise Addition:\n", broadcasted_sum)

Original Data:
 [[1 2 3]
 [4 5 6]]

After Scalar Addition (+10):
 [[11 12 13]
 [14 15 16]]

After Row-wise Addition:
 [[101 202 303]
 [104 205 306]]


#Aggregations (Axis Logic)

Goal: Learn to summarize data by rows (samples) or columns (features).

In [11]:
# Simulating 3 students' scores in 2 subjects
scores = np.array([
    [85, 90], 
    [70, 80], 
    [95, 85]
])

# Axis 0: Columns (Average per subject)
subject_avg = np.mean(scores, axis=0)

# Axis 1: Rows (Average per student)
student_avg = np.mean(scores, axis=1)

print("Scores Matrix:\n", scores)
print("\nAverage per Subject (Axis 0):", subject_avg)
print("Average per Student (Axis 1):", student_avg)

Scores Matrix:
 [[85 90]
 [70 80]
 [95 85]]

Average per Subject (Axis 0): [83.33333333 85.        ]
Average per Student (Axis 1): [87.5 75.  90. ]


#Random Initialization

Goal: The first step in building any Neural Network.

In [12]:
# Generate a 3x3 matrix of random weights
weights = np.random.rand(3, 3)

print("Randomly Initialized Weights:\n", weights)

Randomly Initialized Weights:
 [[0.71560407 0.39313832 0.25569526]
 [0.24741754 0.2147707  0.22336348]
 [0.8136317  0.5670751  0.62232349]]
