#High-Dimensional Tensors

Goal: Move beyond 2D tables. In Deep Learning, data (especially images and video) exists in "Tensors."

#Understanding Shapes

In [3]:
# 1D: Vector (e.g., list of feature values)
vector = np.array([10, 20, 30])

# 2D: Matrix (e.g., a standard dataset table)
matrix = np.array([[1, 2], [3, 4]])

# 3D: Tensor (e.g., a color image: Height x Width x RGB Channels)
tensor_3d = np.random.rand(64, 64, 3)

print(f"Vector Shape: {vector.shape}")
print(f"Matrix Shape: {matrix.shape}")
print(f"3D Tensor Shape: {tensor_3d.shape}")

Vector Shape: (3,)
Matrix Shape: (2, 2)
3D Tensor Shape: (64, 64, 3)


#Reshaping (The "Data Prep" Skill)

Why: Most models require input in a specific shape. For example, flattening an image into a single row.

In [4]:
# Create a 4x4 'Image'
image = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 Matrix:\n", image)

# Flatten it to a 1D array (16 elements)
flattened = image.reshape(-1) 
print("\nFlattened to 1D:\n", flattened)

# Reshape to 8x2
reshaped_8x2 = image.reshape(8, 2)
print("\nReshaped to 8x2:\n", reshaped_8x2)

Original 4x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Flattened to 1D:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

Reshaped to 8x2:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
